import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Main from '../components/Main'
import More from '../components/More'
import NavBar from '../components/NavBar'
import Quote from '../components/Quote'
import Solution from '../components/Solution'
import Solutions from '../components/Solutions'
import Sub from '../components/Sub'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecox-Innovative Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Main />
      <More />
      <About />
      <Solution/>
      <Solutions/>
      <Quote/>
      <Sub/>
      <Contact/>
      <Footer/>
    </div>
  )
}
